"""Convert Arduino .ino sketches to MikroDuino-compatible .cpp files."""
from __future__ import annotations

import os
import re
import shutil

_INC_ARDUINO_RE = re.compile(r'^\s*#\s*include\s*[<"]Arduino\.h[>"]', re.MULTILINE)
_SETUP_RE       = re.compile(r'\bvoid\s+setup\s*\(\s*\)')
_LOOP_RE        = re.compile(r'\bvoid\s+loop\s*\(\s*\)')
_MAIN_RE        = re.compile(r'\bint\s+main\s*\(')


def convert_ino(content: str, filename: str = "", add_main: bool = True) -> str:
    """Return .cpp source equivalent to the given .ino content.

    Prepends #include <Arduino.h> (unless already present) and, when
    add_main=True and both setup()/loop() signatures are detected, emits
    ARDUINO_MAIN() which expands to a correct int main() via the compat layer.
    """
    has_arduino_h = bool(_INC_ARDUINO_RE.search(content))
    has_setup     = bool(_SETUP_RE.search(content))
    has_loop      = bool(_LOOP_RE.search(content))

    parts: list[str] = []
    if filename:
        parts.append(f"// Imported from: {filename}")
    parts.append("// Generated by MikroDuino IDE")
    parts.append("")
    if not has_arduino_h:
        parts.append("#include <Arduino.h>")
        parts.append("")
    if add_main and has_setup and has_loop:
        parts.append("ARDUINO_MAIN()")
        parts.append("")
    parts.append(content.rstrip())
    parts.append("")
    return "\n".join(parts)


def project_has_main(source_files: list[str], project_path: str) -> bool:
    """Return True if any existing project source file defines int main(."""
    for rel in source_files:
        abs_path = os.path.join(project_path, rel)
        try:
            with open(abs_path, encoding="utf-8", errors="ignore") as f:
                if _MAIN_RE.search(f.read()):
                    return True
        except OSError:
            pass
    return False


def import_ino(ino_path: str, dest_dir: str) -> list[str]:
    """Import an Arduino sketch into dest_dir.

    Converts the named .ino to .cpp (with ARDUINO_MAIN), converts any
    sibling .ino files (helper tabs) to .cpp (without ARDUINO_MAIN), and
    copies sibling .h/.hpp headers verbatim.

    Returns absolute paths of all created/copied files.
    """
    os.makedirs(dest_dir, exist_ok=True)

    ino_dir  = os.path.dirname(os.path.abspath(ino_path))
    ino_base = os.path.basename(ino_path)
    created: list[str] = []

    # Primary .ino → .cpp with ARDUINO_MAIN
    with open(ino_path, encoding="utf-8", errors="ignore") as f:
        content = f.read()
    cpp_path = os.path.join(dest_dir, os.path.splitext(ino_base)[0] + ".cpp")
    with open(cpp_path, "w", encoding="utf-8") as f:
        f.write(convert_ino(content, ino_base, add_main=True))
    created.append(cpp_path)

    # Sibling files in the same example directory
    try:
        for entry in sorted(os.scandir(ino_dir), key=lambda e: e.name.lower()):
            if not entry.is_file() or entry.name == ino_base:
                continue
            ext = os.path.splitext(entry.name)[1].lower()
            if ext == ".ino":
                with open(entry.path, encoding="utf-8", errors="ignore") as f:
                    sub = f.read()
                sibling_cpp = os.path.join(
                    dest_dir, os.path.splitext(entry.name)[0] + ".cpp"
                )
                with open(sibling_cpp, "w", encoding="utf-8") as f:
                    f.write(convert_ino(sub, entry.name, add_main=False))
                created.append(sibling_cpp)
            elif ext in (".h", ".hpp"):
                dest = os.path.join(dest_dir, entry.name)
                shutil.copy2(entry.path, dest)
                created.append(dest)
    except OSError:
        pass

    return created
